### ISSUE TITLE
Running the xiboside app

### ISSUE THREAD

**Issue by reemaRaven** [ajiwo/xiboside#6]
Hi,

I am facing this issues as below : 
1. Running xiboside doesn't work. Have to run this way : **python xiboside**
2. when running **python xiboside  -c xiboside_config.json**
where I have created xiboside_config.json contents as  :
(omitting the actual server URL and serverkey.) It doesn't generate the config file on its own. So I created it and fed it.

{
    "saveDir": "/tmp/xibot",
    "url": "http://xxxx.com/",
    "serverKey": "yyyy",
    "strTimeFmt": "%Y-%m-%d %H:%M:%S",
    "cmsTzOffset": 5 * 3600,  # GMT+5
    "res_file_ext": ".html",
    "layout_file_ext": ".xml",
    "xmdsVersion": 4,
    "xmrPubUrl": "tcp://localhost:5550",
}

3. On running with the config file - gives empty errror -

```
E:\>python xiboside
qt.qpa.gl: Unable to disable rotation.
Traceback (most recent call last):
  File "xiboside", line 29, in <module>
    cfg = xibo.XiboConfig(args.config)
  File "xibo.py", line 19, in __init__
    self.load()
  File "xibo.py", line 46, in load
    for k, v in tmp.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```
[xiboside_config.zip](https://github.com/ajiwo/xiboside/files/2864526/xiboside_config.zip)

Would be great if you could give some pointers. Ideally, it should pick up the config file that is fed to the command.

Thanks,
Reema

**Comment by rodolphopivetta** [comment]
Hi @reemaRaven, I think you're using python3 as default. The xiboside code is implemented to run with python2. Make sure you have python2 installed and try something like `python2 xiboside`

**Comment by reemaRaven** [comment]
Hi,

Thanks for your reply! Really appreciate.
Yes, I was using python3.6. So I had modified the code as per that, but still a lot of unknown dependencies.

I ran the code in 2.7 where there were a few packages needed to be installed.
Still post installation of crypto, the code keeps saying "no module named crypto".
Am I still missing something?

![image](https://user-images.githubusercontent.com/7135413/53004262-ce086800-3456-11e9-91d8-458a2038b5f6.png)

![image](https://user-images.githubusercontent.com/7135413/53004433-2f303b80-3457-11e9-9c99-8587a6311980.png)

Thanks!
Reema

**Comment by rodolphopivetta** [comment]
In Linux I usually install `python-crypto`, for example in Ubuntu: `sudo apt-get install python-crypto`.

You can try to install `pycrypto` from pip: `pip install pycrypto` but I don't have sure if it will work on Windows.

**Comment by reemaRaven** [comment]
After a lot of efforts I am stuck at this error -
![image](https://user-images.githubusercontent.com/7135413/53079816-446f9d80-351d-11e9-80b4-2735c4f9d21a.png)

Then saw this  : https://github.com/dlitz/pycrypto/issues/238
Pycrypto is no longer supported.
They ask me to work with pycryptodome. Installed the same on python2.7
**"
from Crypto import Random
ImportError: No module named Crypto
"**

Still says the same error :(
